const fs=require('node:fs');
const {chromium}=require('playwright-core');
let runningBrowser;
async function main(){
 const tokens={reader:process.env.LOCAL_READER_TOKEN,operator:process.env.LOCAL_OPERATOR_TOKEN};if(!tokens.reader||!tokens.operator)throw new Error('Both local role tokens are required');
 const output=process.env.EVIDENCE_DIR||'evidence/browser-'+new Date().toISOString().replace(/[:.]/g,'-');fs.mkdirSync(output,{recursive:true});
 const base=process.env.DASHBOARD_URL||'http://127.0.0.1:4100';
 const browser=await chromium.launch({headless:true,...(process.env.BROWSER_EXECUTABLE?{executablePath:process.env.BROWSER_EXECUTABLE}:{channel:process.env.BROWSER_CHANNEL||'msedge'})});runningBrowser=browser;
 const context=await browser.newContext({viewport:{width:1440,height:1000},recordVideo:{dir:output}});
 const page=await context.newPage();
 const errors=[];page.on('pageerror',error=>errors.push(error.message));
 await page.goto(base+'/?source=cloud',{waitUntil:'domcontentloaded',timeout:60000});
 await page.getByLabel('Local access token').fill(tokens.operator);
 await page.getByRole('button',{name:'Connect locally'}).click();
 await page.getByText('Connected to local API. Simulated measurements. Access: Operator.',{exact:true}).waitFor({timeout:30000});
 await page.locator('[data-testid="boot-overlay"]').waitFor({state:'hidden',timeout:15000});
 const ack=page.getByRole('button',{name:'Ack',exact:true});
 if(!(await ack.count()))throw new Error('Seed an unacknowledged alarm before the browser proof');
 const acknowledgement=page.waitForResponse(r=>r.url().includes('/acknowledgements')&&r.request().method()==='POST');
 await ack.first().click();
 const response=await acknowledgement;
 if(response.status()!==200)throw new Error('Acknowledgement failed: '+response.status());
 const alarm=await response.json();
 if(!alarm.acknowledged_at)throw new Error('Server did not persist acknowledgement');
 await page.reload({waitUntil:'domcontentloaded'});
 await page.getByLabel('Local access token').fill(tokens.operator);
 await page.getByRole('button',{name:'Connect locally'}).click();
 await page.getByText('Connected to local API. Simulated measurements. Access: Operator.',{exact:true}).waitFor({timeout:30000});
 await page.locator('[data-testid="boot-overlay"]').waitFor({state:'hidden',timeout:15000});
 await page.screenshot({path:output+'/dashboard-operator.png',fullPage:true});
 const reader=await browser.newContext({viewport:{width:1440,height:1000}});
 const second=await reader.newPage();await second.goto(base+'/?source=cloud',{waitUntil:'domcontentloaded',timeout:60000});
 await second.getByLabel('Local access token').fill(tokens.reader);await second.getByRole('button',{name:'Connect locally'}).click();
 await second.getByText('Connected to local API. Simulated measurements. Access: Reader.',{exact:true}).waitFor({timeout:30000});
 if(await second.getByRole('button',{name:'Ack',exact:true}).count())throw new Error('Reader can see an Ack control');
 await second.locator('[data-testid="boot-overlay"]').waitFor({state:'hidden',timeout:15000});
 const stored=await second.evaluate(async token=>(await fetch('/api/v1/alarms',{headers:{Authorization:'Bearer '+token}})).json(),tokens.reader);
 const persisted=stored.alarms.find(row=>row.id===alarm.id);
 if(!persisted||persisted.acknowledged_at!==alarm.acknowledged_at)throw new Error('Second session cannot observe the persisted acknowledgement');
 await second.screenshot({path:output+'/dashboard-reader.png',fullPage:true});
 await reader.close();await context.close();await browser.close();
 fs.writeFileSync(output+'/result.json',JSON.stringify({operator:true,readerHasNoAck:true,acknowledgementSurvivesReloadAndSecondSession:true,alarmId:alarm.id,browserErrors:errors,provenance:'real browser and API, simulated measurements',date:new Date().toISOString()},null,2));
 if(errors.length)throw new Error('Browser errors: '+errors.join(';'));
 console.log('Browser role checks and screenshots completed');
}
main().catch(async error=>{console.error(error.message);await runningBrowser?.close();process.exitCode=1;});
